DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP FUNCTION IF EXISTS generate_order_number() CASCADE;
DROP SEQUENCE IF EXISTS order_number_seq CASCADE;
